"""create all tables

Revision ID: 0451e24920fb
Revises: 9ea5206d8e45
Create Date: 2025-10-02 16:17:28.277284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0451e24920fb'
down_revision: Union[str, Sequence[str], None] = '9ea5206d8e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=True)
    # ### end Alembic commands ###
