"""create all tables1

Revision ID: e1184aa63706
Revises: 0451e24920fb
Create Date: 2025-10-03 17:57:13.184223

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e1184aa63706'
down_revision: Union[str, Sequence[str], None] = '0451e24920fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
